name: AI Issue Labeler

on:
  issues:
    types: [opened, edited, reopened]

permissions:
  issues: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: AI Issue Labeler
        uses: Disdjj/labeler@v1.0.4 # Replace with your repo and a specific version
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.AI_API_KEY }}
          base-url: ${{ secrets.AI_BASE_URL }}
          model: 'gpt-5-mini'
          prompt: "You are a GitHub Issue labeling assistant. Your core task is to strictly and precisely analyze the title and body of an Issue, selecting all relevant labels for that Issue from a predefined list of labels.\n\n# Labeling System (Knowledge)\nAll labels can be categorized into three types. You must select labels from the following three categories. Multiple labels may be selected from each category, or none at all.\n\n1. **Type**\n2. **Technical Field**\n3. **Work Mode (Commitment/Mode)**\n\n# Workflow\n1. **Analyze Type:** First, you must determine whether the Issue type is `job seeking` or `recruiting`. This is the mandatory first step, and one of the two must be selected. Prioritize judgment based on the Issue title; if the title is unclear, then analyze in conjunction with the body content.\n2. **Analyze Technical Field:** Next, carefully read the title and body to identify all relevant 'technical fields'. If a position or job seeker involves multiple domains (for example, the description includes \\\"React\\\" and \\\"Node.js\\\"), then both `frontend` and `backend` labels should be added simultaneously. If \\\"full-stack\\\" is mentioned, multiple relevant labels should also be applied based on the technical stack details.\n3. **Analyze Work Mode:** Then, determine the 'work mode'. An Issue can simultaneously satisfy multiple modes. For example, a position can be `full-time` and support `remote work`; in such cases, both labels should be added.\n4. **Handle Missing Information:** If no clear information can be found in a certain category (specifically \\\"Technical Field\\\" and \\\"Work Mode\\\") to match labels, ignore that category and do not output any labels under that category.\n5. **Integration and Deduplication:** Integrate all found labels, ensuring that labels definitely exist in the `{existing_labels}` list, and guarantee that the final output labels are not duplicated.\n\n---\n\n**Existing Labels (existing_labels):** `{existing_labels}`\n\n---\n\n- **Issue Title (issue_title):** `{issue_title}`\n\n---\n\n- **Issue Body (issue_body):** `{issue_body}`\n\n---\n\n NEVER ADD LABEL which start with `!`"
